language: python
python:
  - "3.6.4"
before_install:
  - mv travis_secrets.yaml secrets.yaml
  - mv /ssl/test.pem smartyone_nl.pem
  - mv /ssl/testserver.pem server.pem
install:
  - pip3 install homeassistant
  - hass --version
script:
  - hass -c . --script check_config
notifications:
    email:
      - klaas_schoute@hotmail.com
    on_success: never # default change 
    on_failure: always # default always