language: python
python:
  - "3.7.0"
before_install:
  - mv travis_secrets.yaml secrets.yaml
  - touch ./home-assistant_v2.db
  - touch ./home-assistant.log
  - touch ./OZW_Log.txt
install:
  - pip3 install homeassistant
  - hass --version
script:
  - hass -c . --script check_config
notifications:
    email:
      - klaas_schoute@hotmail.com
    on_success: never # default change 
    on_failure: always # default always